export default function Terms() {
  return (
    <main className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="bg-white rounded-lg shadow-md p-8 space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-3">Agreement to Terms</h2>
            <p className="text-gray-700">
              By accessing and using DealPilot (&quot;the Service&quot;), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Description of Service</h2>
            <p className="text-gray-700">
              DealPilot is a HubSpot integration that provides AI-powered deal intelligence, including:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 mt-3">
              <li>Deal health analysis and win probability scoring</li>
              <li>Automated follow-up email drafting</li>
              <li>AI-generated next steps and task creation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">User Responsibilities</h2>
            <p className="text-gray-700 mb-3">
              As a user of DealPilot, you agree to:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2">
              <li>Provide accurate and current information</li>
              <li>Maintain the security of your HubSpot account credentials</li>
              <li>Use the Service in compliance with all applicable laws and regulations</li>
              <li>Not misuse or attempt to gain unauthorized access to the Service</li>
              <li>Review AI-generated content before sending to customers</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">AI-Generated Content</h2>
            <p className="text-gray-700">
              DealPilot uses artificial intelligence to generate insights, recommendations, and content. 
              You acknowledge that:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 mt-3">
              <li>AI-generated content should be reviewed before use</li>
              <li>We do not guarantee the accuracy of AI predictions or recommendations</li>
              <li>You are responsible for all communications sent using content generated by the Service</li>
              <li>AI outputs are suggestions and should be evaluated based on your specific business context</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Intellectual Property</h2>
            <p className="text-gray-700">
              The Service, including its design, functionality, and content, is owned by Das Group LLC and protected by intellectual property laws. 
              You may not copy, modify, distribute, or reverse engineer any part of the Service without our written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Data Usage</h2>
            <p className="text-gray-700">
              By using DealPilot, you grant us permission to:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 mt-3">
              <li>Access your HubSpot data as necessary to provide the Service</li>
              <li>Process your data through third-party AI services (OpenAI)</li>
              <li>Use anonymized, aggregated data to improve the Service</li>
            </ul>
            <p className="text-gray-700 mt-3">
              Your data usage is governed by our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Limitations of Liability</h2>
            <p className="text-gray-700">
              To the maximum extent permitted by law, Das Group LLC shall not be liable for:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 mt-3">
              <li>Any indirect, incidental, special, or consequential damages</li>
              <li>Loss of profits, data, or business opportunities</li>
              <li>Damages resulting from AI-generated recommendations or content</li>
              <li>Service interruptions or data loss</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Service Availability</h2>
            <p className="text-gray-700">
              We strive to maintain high availability but do not guarantee uninterrupted access to the Service. 
              We may suspend or terminate the Service for maintenance, updates, or other reasons without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Termination</h2>
            <p className="text-gray-700">
              You may terminate your use of the Service at any time by uninstalling the app from your HubSpot account. 
              We reserve the right to suspend or terminate your access to the Service if you violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Changes to Terms</h2>
            <p className="text-gray-700">
              We may modify these Terms at any time. 
              Continued use of the Service after changes constitutes acceptance of the new Terms. 
              We will make reasonable efforts to notify users of significant changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Governing Law</h2>
            <p className="text-gray-700">
              These Terms are governed by the laws of the United States and the state in which Das Group LLC is registered, 
              without regard to conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">Contact Information</h2>
            <p className="text-gray-700">
              For questions about these Terms of Service, please contact:
            </p>
            <p className="text-gray-700 mt-3">
              <strong>Email:</strong> <a href="mailto:support@dasgroupllc.com" className="text-blue-600 hover:underline">support@dasgroupllc.com</a>
              <br />
              <strong>Company:</strong> Das Group LLC
            </p>
          </section>

          <section>
            <p className="text-gray-700">
              <strong>Last Updated:</strong> February 22, 2025
            </p>
          </section>
        </div>

        <div className="mt-8 text-center">
          <a href="/" className="text-blue-600 hover:underline">← Back to Home</a>
        </div>
      </div>
    </main>
  );
}
